version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"

  website:
    build:
      context: .
      dockerfile: website.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - API_PROXY=http://server:8080
      - PORT=5000
      - HOST=0.0.0.0