name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: v1.26.0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Verify dependencies
      run: go mod verify
    
      
    - name: Setup sqlc
      run: sqlc generate
    
    - name: Go Generate
      run: go generate ./... && git diff --exit-code

    - name: Go Build
      run: go build -o /dev/null ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...


